name: EconomyX
version: '${version}'
main: oasis.economyx.EconomyX
api-version: '1.20'
commands:
  create:
    description: 생성 명령어입니다.
    usage: /create
    aliases: [new, 신규, 생성, 추가]
  balance:
    description: 내 잔고를 조회합니다.
    usage: /balance [통화]
    aliases: [bal, balance, 잔고]
  sudo:
    description: 타인의 명의로 명령어를 실행합니다.
    usage: /sudo 대상 명령어
    aliases: [s, d, sd, as, 대신, 대변]
  setaddress:
    description: 주소지를 설정합니다.
    usage: /setaddress
    aliases: [sa, sh, sethome, setaddress, 주소지설정, 주소설정, 홈설정]
  pay:
    description: 송금 명령어입니다.
    usage: /pay 수신인 통화 금액
    aliases: [p, 송금]
  message:
    description: 메시지를 발신합니다.
    usage: /message 수신인 내용
    aliases: [w, dm, msg, t, tell, 디엠, 메시지]
  reply:
    description: 수신한 메시지에 답변을 보냅니다.
    usage: /reply [수신인] 내용
    aliases: [r, 답변, 답장]